# Generated by Django 3.2.7 on 2021-10-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
